apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service_address: http://eureka-0.eureka:8769/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None   # Change to LoadBalancer if you want external access
  selector:
    app: eureka
  ports:
    - port: 8769        # Service port exposed inside cluster
      name: eureka # Maps to containerPort in Deployment

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: eureka   # Must match the headless service name
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: dadyapatil/service-registry:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8769
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  type: NodePort   # Change to LoadBalancer if you want external access
  selector:
    app: eureka
  ports:
    - port: 80        # Service port exposed inside cluster
      targetPort: 8769 # Maps to containerPort in Deployment